### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by enggazzar** [arsy1995/GoogleMapsRippleEffect#5]
com.arsy.googlemapsrippleeffect E/dalvikvm-heap: Out of memory on a 67108880-byte allocation.

**Comment by aarsy** [comment]
Which mobile device you are using . I have came across this issue before but have not implemented it yet . This issue is arising when I'm creating a bitmap of larger size than it is supported by the mobile device. I have not resized the bitmap accordingly. What you can do is assign lesser width and height to the drawable or bitmap in the code. If you can resolve this issue then please create a pull request I will merge it right here

**Comment by enggazzar** [comment]
there are library compress image but i will try fix this

**Comment by Hristijan95** [comment]
You can make the background drawable size smaller, for example 500 x 500dp, to temporary avoid this error.

**Comment by mradzinski** [comment]
I'm experiencing this on every single one of my physical test devices:
- Nexus 5
- Nexus 5s
- Samsung Galaxy S6
- Samsung Galaxy Note 2

Also happening on the emulator as well.

**Comment by aarsy** [comment]
Have you tried the above solution which I have told?

**Comment by irwing844** [comment]
hello, do you try fix this?

**Comment by microcian** [comment]
same issue @Hristijan95 please tell us where we have to change or add the size ?? I've tested this code 5 devices and all got exception

**Comment by Hristijan95** [comment]
@abdulrahmanmajeed , this is the file: https://github.com/aarsy/GoogleMapsAnimations/blob/master/googlemapsanimations/src/main/res/drawable/background.xml

You can't change this, unless you re-create the library yourself, or wait for the creator to update it.

**Comment by aarsy** [comment]
Any PULL request would be appreciated for this bug. Since I'm busy and
can't resolve this issue for couple of months. Please clone the project and
import the "googlemapsanimations" module into your project instead of using
it via gradle dependency command.
And decrease the parameters specied in module's background.xml

Any one who wish to create a pull request after updations also rename
library's bacground.xml to some unique name because it's creating conflict
if same name file exists in your application.

**Comment by enzonotario** [comment]
Hi! When I try to import the module (to modify the file background.xml), the gradle sync gives me an error:
Plugin with id 'com.jfrog.bintray' not found

How can I fix it?

Thanks!

**Comment by enzonotario** [comment]
Well I just copied the MapRipple class and it works fine! Thanks for your work!

Now, I don't want to repeat the animation. I wan't that it run once. How can I do that?

Sorry but I don't know much about android and don't speak english too..

Thanks!

**Comment by mradzinski** [comment]
@enzonotario, how's your issue related to an OOM one? Please, next time open another issue if the ones open are not related to yours. Second, there's no built-in way for what you are trying to achieve, however, since you already copied the MapRipple class to your project, line 181 sets an infinite loop to the animation, you should check there to only repeat it once.

**Comment by enzonotario** [comment]
Well I come to this issue because I also have the "Out of memory" error. 
I comment that line and now it works how I want.

Sorry, but maybe if I speak english I can explain better...

Thanks, and sorry again

**Comment by fukemy** [comment]
wtf !
        android:width="1500dp"
        android:height="1500dp"
How can you let the big drawable like that....

**Comment by fukemy** [comment]
plz fix and update

**Comment by felixeduardo15** [comment]
java.lang.OutOfMemoryError
                                                                        at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
                                                                        at android.graphics.Bitmap.access$000(Bitmap.java:29)
                                                                        at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1446)
                                                                        at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1438)
                                                                        at com.google.android.gms.maps.model.internal.b.onTransact(:com.google.android.gms.DynamiteModulesB:101)
                                                                        at android.os.Binder.transact(Binder.java:364)
                                                                        at szk.a(:com.google.android.gms:242)
                                                                        at srn.a(:com.google.android.gms:1252)
                                                                        at srp.a(:com.google.android.gms:184)
                                                                        at srh.a(:com.google.android.gms:6164)
                                                                        at szj.onTransact(:com.google.android.gms:106)
                                                                        at android.os.Binder.transact(Binder.java:364)
                                                                        at com.google.android.gms.maps.model.internal.zza$zza$zza.zze(Unknown Source)
                                                                        at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
                                                                        at com.arsy.maps_library.MapRipple$3.run(MapRipple.java:159)
                                                                        at android.os.Handler.handleCallback(Handler.java:733)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:136)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
                                                                        at dalvik.system.NativeStart.main(Native Method)
