### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by shubhank12** [arsy1995/GoogleMapsRippleEffect#8]
Its work perfect in 6.0.1 but error in some device mostly in lollipop 

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.coincide.ridetog, PID: 12679
                                                   java.lang.OutOfMemoryError: Failed to allocate a 81000012 byte allocation with 16775712 free bytes and 60MB until OOM
                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                       at android.graphics.Bitmap.nativeCreateFromParcel(Native Method)
                                                       at android.graphics.Bitmap.access$000(Bitmap.java:32)
                                                       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1484)
                                                       at android.graphics.Bitmap$1.createFromParcel(Bitmap.java:1476)
                                                       at com.google.android.gms.maps.model.internal.b.onTransact(:com.google.android.gms.DynamiteModulesB:101)
                                                       at android.os.Binder.transact(Binder.java:380)
                                                       at uyr.a(:com.google.android.gms:242)
                                                       at uqu.a(:com.google.android.gms:1252)
                                                       at uqw.a(:com.google.android.gms:187)
                                                       at uqo.a(:com.google.android.gms:6164)
                                                       at uyq.onTransact(:com.google.android.gms:106)
                                                       at android.os.Binder.transact(Binder.java:380)
                                                       at com.google.android.gms.maps.model.internal.zza$zza$zza.zze(Unknown Source)
                                                       at com.google.android.gms.maps.model.BitmapDescriptorFactory.fromBitmap(Unknown Source)
                                                       at com.arsy.maps_library.MapRipple$1.run(MapRipple.java:133)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5247)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

**Comment by cheetahdeliverys** [comment]
I have the same problem

**Comment by shubhank12** [comment]
not resolve yet

**Comment by shubhank12** [comment]
@cheetahdeliverys instead of this i use another animation if you want i can share the code its work fine in every mobile i tested that

**Comment by felixeduardo15** [comment]
@shubhank12  can you bring example to use this library?

**Comment by amanjain08** [comment]
@cheetahdeliverys  I would appreciate if you can share the code.

**Comment by shubhank12** [comment]
@cheetahdeliverys @amanjain08  here is java class i use https://gist.github.com/shubhank12/1e1d3db0cdd1f6ed61b47b58260c3b7d

**Comment by amanjain08** [comment]
@cheetahdeliverys Thank you for quick response. But how are you using that view to show ripple effect on map marker

**Comment by shubhank12** [comment]
private MapRadar mapRadar;


/////////////////////////////////////////////////////////////////////////////////
Marker marker = mMap.addMarker(new MarkerOptions()
                                    .position(new LatLng(userSourceLat, userSourceLng))
                                    .title("No match Found")
                                    .snippet("Searching for Match"));
                            mRadarView.setShowCircles(true);
                            if (mRadarView != null) mRadarView.startAnimation();
////////////////////////////////////////////////////////////////////////////////////


Note: i don't know for what reason you need that animation. but i use that by default marker is place in center of the map. i place map inside the relativelayout and i also place raderView at the center of the RelativeLayout.

////////////////////////////////////////////////////////////////////////////////////////////


    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@+id/bootomLayout">

        <fragment
            android:id="@+id/mapView"
            class="com.google.android.gms.maps.SupportMapFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

        <your.packagename.RadarView
            android:id="@+id/radarView"
            android:layout_width="240dp"
            android:layout_height="240dp"
            android:layout_centerInParent="true"
            android:visibility="gone" />

    </RelativeLayout>
////////////////////////////////////////////////////////////////////////////////

@amanjain08 if you specify the reason of anim maybe i help more

**Comment by amanjain08** [comment]
@shubhank12 You haven't using ripple view on marker on map. I want ripple view on marker that could be anywhere on map. You have fixed your view on center of screen. For my case there could be a multiple marker on map so I want the ripple view for all that markers.

**Comment by shubhank12** [comment]
@amanjain08 ya thats true i use different animation which differ from your requirement

**Comment by Ok-Alex** [comment]
Also getting OutOfMemory for MapRadar. @aarsy did you checked it?

**Comment by Ok-Alex** [comment]
I was managed to fix the issue. I downloaded sources of GoogleMapsAnimations to my project and updated play services version in gradle. Tested on API 19, 24, 25

**Comment by fjn89** [comment]
@Ok-Alex what exactly did you do? I cant solve the problem

**Comment by hanuor** [comment]
If you have any modified version of the code which resolves this issue then please issue a pull request and we'll merge. 
Thanks.

**Comment by pranjal-joshi** [comment]
Same Fatal issue on some devices, error occurence varies from device to device. Please update the new version with resolved issue.

**Comment by charlescruz07** [comment]
have you guys found a fix for this?

**Comment by ashishguptasanu** [comment]
This error is thrown by the Java Virtual Machine (JVM) when an object cannot be allocated due to lack of memory space and also, the garbage collector cannot free some space.

Add these two lines in your manifest files inside Application Tag:
android:largeHeap="true"
android:hardwareAccelerated="false"

Something like this, It had solved the problem:
`<application
        android:allowBackup="true"
        android:icon="@mipmap/app_logo"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/app_logo"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        android:largeHeap="true"
        android:hardwareAccelerated="false"></application>`

**Comment by pcg92** [comment]
java.lang.OutOfMemoryError: Failed to allocate a 268435468 byte allocation with 16777216 free bytes and 201MB until OOM

Just using one radar

**Comment by yusufonderd** [comment]
same problem on Android 7.1.1

**Comment by chihung93** [comment]
I have the same problem with Android 6.0

**Comment by sebasira** [comment]
Same here! with Nougat

**Comment by nodahikaru** [comment]
Same problem. This Ripple Animation was unable to be used in android any more ?

**Comment by wanglouin1990925** [comment]
same here

**Comment by anudeepreddygopu** [comment]
Even I am facing the same issue

**Comment by aarsy** [comment]
Hello Guys, I would be very thankful to you guys if someone create patch for this issue and raise a PR.

**Comment by hanuor** [comment]
@aarsy Looking into it. I'll see what I can do.

**Comment by dvGomez** [comment]
Hi guys,

I got same error:

`E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb96509f8
05-18 16:19:40.094 32198-32294/test.taxiapp.novotaxi E/AndroidRuntime: FATAL EXCEPTION: GLThread 3019
    Process: test.taxiapp.novotaxi, PID: 32198
    java.lang.IllegalArgumentException: Textures with dimensions8192x8192 are larger than  the maximum supported size 4096x4096
        at com.google.maps.api.android.lib6.gmm6.vector.gl.ag.a(:com.google.android.gms.dynamite_mapsdynamite@17122047@17.1.22 (040308-245988633):75)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.ag.a(:com.google.android.gms.dynamite_mapsdynamite@17122047@17.1.22 (040308-245988633):29)
        at com.google.maps.api.android.lib6.gmm6.api.i.a(:com.google.android.gms.dynamite_mapsdynamite@17122047@17.1.22 (040308-245988633):48)
        at com.google.maps.api.android.lib6.gmm6.api.o.a(:com.google.android.gms.dynamite_mapsdynamite@17122047@17.1.22 (040308-245988633):54)
        at com.google.maps.api.android.lib6.gmm6.vector.bz.a(:com.google.android.gms.dynamite_mapsdynamite@17122047@17.1.22 (040308-245988633):378)
        at com.google.maps.api.android.lib6.gmm6.vector.ax.run(:com.google.android.gms.dynamite_mapsdynamite@17122047@17.1.22 (040308-245988633):85)`

Android 6.0
